# Generated by Django 5.2.5 on 2025-10-25 04:46

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-date"], "verbose_name_plural": "BlogPosts"},
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="content",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="description",
            field=CKEditor5Field(default="Blog"),
        ),
    ]
