# Generated by Django 5.2.5 on 2025-10-25 05:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_options_remove_blogpost_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(default="Blogs"),
        ),
    ]
