# Generated by Django 5.2.5 on 2025-10-25 05:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default="Blogs", verbose_name="Text"
            ),
        ),
    ]
