# Generated by Django 5.2.5 on 2025-08-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="certificate",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="certificate_logos/"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="education_logos/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_photo",
            field=models.ImageField(blank=True, null=True, upload_to="project_photos/"),
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="skill_icons/"),
        ),
    ]
