# Generated by Django 5.2.5 on 2025-08-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_about_profile_photo_certificate_logo_education_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/profile_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/certificate_logos/"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/education_logos/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/project_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/skill_icons/"
            ),
        ),
    ]
