# Generated by Django 5.2.5 on 2025-08-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_about_profile_photo_alter_certificate_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="start_date",
        ),
        migrations.AddField(
            model_name="education",
            name="end_month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="start_month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="end_month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
