# Generated by Django 5.2.5 on 2025-08-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_education_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/social_logos/"
            ),
        ),
    ]
