# Generated by Django 5.2.5 on 2025-10-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_category_alter_skill_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                help_text="Enter a number from 1 to 100, where 100 is expert."
            ),
        ),
    ]
