# Generated by Django 5.2.5 on 2025-10-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_skill_proficiency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="link",
        ),
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="live_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
