# Generated by Django 5.2.5 on 2025-10-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_project_link_project_github_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="about",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
