# Generated by Django 5.2.5 on 2025-10-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_about_address_about_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="resume_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/", verbose_name="Resume (PDF)"
            ),
        ),
    ]
