# Generated by Django 5.2.5 on 2025-10-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_blogpost_categories"),
        ("main", "0011_about_resume_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="related_posts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select any blog posts written about this project.",
                related_name="related_projects",
                to="blog.blogpost",
            ),
        ),
    ]
